/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Quarto;
import classes.Reserva;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuário
 */
public class FormBuscarQuarto extends javax.swing.JFrame {
    private DefaultTableModel modelo;
    /**
     * Creates new form FormBuscarQuarto
     */
    public FormBuscarQuarto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void travarCampo(){
        tfNumeroQuarto2.setEnabled(false);
    }
    
    public void tabelaId(){
        if (tfNumeroQuarto2.getText().equals("    ")){
            JOptionPane.showMessageDialog(null, "Preencha o campo antes de pesquisar.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Quarto q = FormPrincipal.quartoDAO.buscarQuarto(Short.parseShort(tfNumeroQuarto2.getText()));
        if (q != null){
            modelo.addRow(new Object[]{q.getNumQuarto(), q.getValor(), q.getCategoria(), q.getNumCamas(), q.getOcupado()});
        }
        else
           JOptionPane.showMessageDialog(null, "Quarto não encontrada.", "Atenção", JOptionPane.WARNING_MESSAGE); 
    }
    
    public void tabelaDisponiveis(){
        for (Quarto q: FormPrincipal.quartoDAO.getList()){
            if (!q.getOcupado()){
                modelo.addRow(new Object[]{q.getNumQuarto(), q.getValor(), q.getCategoria(), q.getNumCamas(), q.getOcupado()});
            }
        }
    }
    
    public void tabelaIndisponiveis(){
        for (Quarto q: FormPrincipal.quartoDAO.getList()){
            if (q.getOcupado()){
                modelo.addRow(new Object[]{q.getNumQuarto(), q.getValor(), q.getCategoria(), q.getNumCamas(), q.getOcupado()});
            }
        }
    }
    
    public void tabelaTodos(){
        this.tabelaDisponiveis();
        this.tabelaIndisponiveis();
    }
    
   
    
    public Quarto pegaQuarto(){
        int linha = tbQuarto.getSelectedRow();
        
        Quarto q = new Quarto();
        q.setNumQuarto((Short) modelo.getValueAt(linha, 0));
        q.setValor((Float) modelo.getValueAt(linha, 1));
        q.setCategoria((String) modelo.getValueAt(linha, 2));
        q.setNumCamas((Byte) modelo.getValueAt(linha, 3));
        q.setOcupado((Boolean) modelo.getValueAt(linha, 4));
        return q;
    }
    
    public void limparTabela(){
        for (int i = tbQuarto.getRowCount() - 1; i >= 0; i--){
            modelo.removeRow(i);
        }
    }
    
    public Boolean verificaQuarto(short codigo){
        for (Reserva r: FormPrincipal.reservaDAO.getList()){
            if (r.getQuarto().getNumQuarto() == codigo){
                JOptionPane.showMessageDialog(null, "Quarto reservado. Não é possivel excluir/editar.", "Atenção", JOptionPane.WARNING_MESSAGE);
                return false;
            }
        }
        
        return true;
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        bgTipoQuarto = new javax.swing.ButtonGroup();
        lbNumeroQuarto = new javax.swing.JLabel();
        tfNumeroQuarto2 = new javax.swing.JFormattedTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        btBuscarCPF1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbQuarto = new javax.swing.JTable();
        btEditar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btSair1 = new javax.swing.JButton();
        lbImagemQuarto = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNumeroQuarto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNumeroQuarto.setForeground(new java.awt.Color(0, 0, 102));
        lbNumeroQuarto.setText("Número do Quarto:");
        getContentPane().add(lbNumeroQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, 20));

        try {
            tfNumeroQuarto2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfNumeroQuarto2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumeroQuarto2ActionPerformed(evt);
            }
        });
        getContentPane().add(tfNumeroQuarto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 45, 90, 30));

        bgTipoQuarto.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(0, 0, 102));
        jRadioButton1.setText("Todos os Quartos");
        jRadioButton1.setActionCommand("Todos");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        bgTipoQuarto.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(0, 0, 102));
        jRadioButton2.setText("Quartos Disponíveis");
        jRadioButton2.setActionCommand("Disponiveis");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 47, -1, -1));

        bgTipoQuarto.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(0, 0, 102));
        jRadioButton3.setSelected(true);
        jRadioButton3.setText("Por Numero");
        jRadioButton3.setActionCommand("Numero");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, -1, -1));

        bgTipoQuarto.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(0, 0, 102));
        jRadioButton4.setText("Quartos Ocupados");
        jRadioButton4.setActionCommand("Ocupados");
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 72, -1, -1));

        btBuscarCPF1.setBackground(new java.awt.Color(255, 255, 255));
        btBuscarCPF1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBuscarCPF1.setForeground(new java.awt.Color(0, 0, 102));
        btBuscarCPF1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icBuscar.png"))); // NOI18N
        btBuscarCPF1.setText("Buscar");
        btBuscarCPF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarCPF1ActionPerformed(evt);
            }
        });
        getContentPane().add(btBuscarCPF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 120, 50));

        tbQuarto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        tbQuarto.setForeground(new java.awt.Color(0, 0, 102));
        tbQuarto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Quarto", "Valor da Diária", "Categoria", "Nº Camas", "Ocupado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Short.class, java.lang.Float.class, java.lang.String.class, java.lang.Byte.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbQuarto.getTableHeader().setReorderingAllowed(false);
        tbQuarto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbQuartoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbQuarto);
        if (tbQuarto.getColumnModel().getColumnCount() > 0) {
            tbQuarto.getColumnModel().getColumn(0).setPreferredWidth(40);
            tbQuarto.getColumnModel().getColumn(1).setPreferredWidth(50);
            tbQuarto.getColumnModel().getColumn(2).setPreferredWidth(80);
            tbQuarto.getColumnModel().getColumn(3).setPreferredWidth(30);
            tbQuarto.getColumnModel().getColumn(4).setPreferredWidth(30);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 400, 140));

        btEditar.setBackground(new java.awt.Color(255, 255, 255));
        btEditar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEditar.setForeground(new java.awt.Color(0, 0, 102));
        btEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icAtualizar2.png"))); // NOI18N
        btEditar.setText("Editar");
        btEditar.setEnabled(false);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, 50));

        btExcluir.setBackground(new java.awt.Color(255, 255, 255));
        btExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btExcluir.setForeground(new java.awt.Color(0, 0, 102));
        btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icRemoverItem.png"))); // NOI18N
        btExcluir.setText("Excluir");
        btExcluir.setEnabled(false);
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, 51));

        btSair1.setBackground(new java.awt.Color(255, 255, 255));
        btSair1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSair1.setForeground(new java.awt.Color(0, 0, 102));
        btSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icSair.png"))); // NOI18N
        btSair1.setText("Sair");
        btSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSair1ActionPerformed(evt);
            }
        });
        getContentPane().add(btSair1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 320, 110, 51));

        lbImagemQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quarto33.jpg"))); // NOI18N
        getContentPane().add(lbImagemQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 470, 390));

        setSize(new java.awt.Dimension(477, 420));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfNumeroQuarto2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumeroQuarto2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumeroQuarto2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        this.travarCampo();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void btBuscarCPF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarCPF1ActionPerformed
        btEditar.setEnabled(false);
        btExcluir.setEnabled(false);
        
        this.limparTabela();
        this.modelo = (DefaultTableModel) tbQuarto.getModel();
        
        switch(bgTipoQuarto.getSelection().getActionCommand()){
            case "Numero":
                this.tabelaId();
                break;
                
            case "Ocupados":
                this.tabelaIndisponiveis();
                break;
                
            case "Disponiveis":
                this.tabelaDisponiveis();
                break;
                
            case "Todos":
                this.tabelaTodos();
                break;
        }
    }//GEN-LAST:event_btBuscarCPF1ActionPerformed

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        Quarto q = this.pegaQuarto();
        
        if (!this.verificaQuarto(q.getNumQuarto()))
            return;
        
        FormQuarto fq = new FormQuarto();
        fq.setVisible(true);
        fq.qt = q;
        
        this.dispose();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        short codigo = this.pegaQuarto().getNumQuarto();
        
        if (!this.verificaQuarto(codigo))
            return;
        
        
        int opcao = JOptionPane.showConfirmDialog(null, "Deseja mesmo excluir o quarto?", "Confirmação", JOptionPane.WARNING_MESSAGE);
        System.out.println(opcao);
        if (opcao == 0){
            FormPrincipal.quartoDAO.removerQuarto(codigo);
            modelo.removeRow(tbQuarto.getSelectedRow());
        }
        
        btEditar.setEnabled(false);
        btExcluir.setEnabled(false);
        
    }//GEN-LAST:event_btExcluirActionPerformed

    private void btSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSair1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSair1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        tfNumeroQuarto2.setEnabled(true);
        tfNumeroQuarto2.setText("");
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        this.travarCampo();
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        this.travarCampo();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void tbQuartoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbQuartoMouseClicked
        btEditar.setEnabled(true);
        btExcluir.setEnabled(true);
    }//GEN-LAST:event_tbQuartoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBuscarQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBuscarQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBuscarQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBuscarQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBuscarQuarto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgTipoQuarto;
    private javax.swing.JButton btBuscarCPF1;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSair1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbImagemQuarto;
    private javax.swing.JLabel lbNumeroQuarto;
    private javax.swing.JTable tbQuarto;
    private javax.swing.JFormattedTextField tfNumeroQuarto2;
    // End of variables declaration//GEN-END:variables
}
