/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Quarto;
import java.util.Enumeration;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;

/**
 *
 * @author Usuário
 */
public class FormQuarto extends javax.swing.JFrame {
    public Quarto qt = null;
    /**
     * Creates new form FormQuarto
     */
    public FormQuarto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButtonCasado = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        bgCategoria = new javax.swing.ButtonGroup();
        bgCamas = new javax.swing.ButtonGroup();
        lbValorDiaria = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rbQuartoSimples = new javax.swing.JRadioButton();
        rbSuiteSimples = new javax.swing.JRadioButton();
        rbSuitePresidencial = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        tfDiaria = new javax.swing.JTextField();
        btBuscarCPF = new javax.swing.JButton();
        btCadastrar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btAtualizar = new javax.swing.JButton();
        tfNumeroQuarto = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Estado Civil", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton2.setText("Solteiro");
        jRadioButton2.setActionCommand("Solteiro");

        jRadioButtonCasado.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButtonCasado.setText("Casado");
        jRadioButtonCasado.setActionCommand("Casado");

        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton3.setText("Divorciado");
        jRadioButton3.setActionCommand("Divorciado");

        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton4.setText("União Estável");
        jRadioButton4.setActionCommand("União Estável");

        jRadioButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jRadioButton5.setText("Viúvo");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButton2)
                .addGap(26, 26, 26)
                .addComponent(jRadioButtonCasado)
                .addGap(38, 38, 38)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jRadioButton5)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButtonCasado)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Quarto");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbValorDiaria.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbValorDiaria.setForeground(new java.awt.Color(0, 0, 102));
        lbValorDiaria.setText("Valor da Diária");
        getContentPane().add(lbValorDiaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 110, 20));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Categoria:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(0, 0, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bgCategoria.add(rbQuartoSimples);
        rbQuartoSimples.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbQuartoSimples.setForeground(new java.awt.Color(0, 0, 102));
        rbQuartoSimples.setText("Quarto Simples");
        rbQuartoSimples.setActionCommand("Quarto Simples");
        rbQuartoSimples.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbQuartoSimplesActionPerformed(evt);
            }
        });
        jPanel4.add(rbQuartoSimples, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 27, -1, -1));

        bgCategoria.add(rbSuiteSimples);
        rbSuiteSimples.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbSuiteSimples.setForeground(new java.awt.Color(0, 0, 102));
        rbSuiteSimples.setText("Suíte Simples");
        rbSuiteSimples.setActionCommand("Suite Simples");
        jPanel4.add(rbSuiteSimples, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 55, -1, -1));

        bgCategoria.add(rbSuitePresidencial);
        rbSuitePresidencial.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rbSuitePresidencial.setForeground(new java.awt.Color(0, 0, 102));
        rbSuitePresidencial.setText("Suíte Presidencial");
        rbSuitePresidencial.setActionCommand("Suite Presidente");
        rbSuitePresidencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbSuitePresidencialActionPerformed(evt);
            }
        });
        jPanel4.add(rbSuitePresidencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 170, 120));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Número de Camas:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N
        jPanel6.setForeground(new java.awt.Color(0, 51, 102));

        bgCamas.add(rb1);
        rb1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rb1.setForeground(new java.awt.Color(0, 0, 102));
        rb1.setText("1 Cama");
        rb1.setActionCommand("1");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        bgCamas.add(rb2);
        rb2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rb2.setForeground(new java.awt.Color(0, 0, 102));
        rb2.setText("2 Camas");
        rb2.setActionCommand("2");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        bgCamas.add(rb3);
        rb3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rb3.setForeground(new java.awt.Color(0, 0, 102));
        rb3.setText("3 Camas");
        rb3.setActionCommand("3");

        bgCamas.add(rb4);
        rb4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        rb4.setForeground(new java.awt.Color(0, 0, 102));
        rb4.setText("4 Camas");
        rb4.setActionCommand("4");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rb1)
                .addGap(26, 26, 26)
                .addComponent(rb2)
                .addGap(38, 38, 38)
                .addComponent(rb3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rb4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1)
                    .addComponent(rb2)
                    .addComponent(rb3)
                    .addComponent(rb4))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 450, -1));
        jPanel6.getAccessibleContext().setAccessibleParent(jPanel6);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 102));
        jLabel7.setText("Número do Quarto (4 Dígitos):");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 170, 20));

        tfDiaria.setText("0.00");
        getContentPane().add(tfDiaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 130, 30));

        btBuscarCPF.setBackground(new java.awt.Color(255, 255, 255));
        btBuscarCPF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBuscarCPF.setForeground(new java.awt.Color(0, 0, 102));
        btBuscarCPF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icBuscar.png"))); // NOI18N
        btBuscarCPF.setText("Buscar Quarto");
        btBuscarCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarCPFActionPerformed(evt);
            }
        });
        getContentPane().add(btBuscarCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 150, 40));

        btCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCadastrar.setForeground(new java.awt.Color(0, 0, 102));
        btCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icIncluirCliente.png"))); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 325, 124, 51));

        btLimpar.setBackground(new java.awt.Color(255, 255, 255));
        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(0, 0, 102));
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icLimpar.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 325, 107, 51));

        btSair.setBackground(new java.awt.Color(255, 255, 255));
        btSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSair.setForeground(new java.awt.Color(0, 0, 102));
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icSair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 325, 107, 51));

        btAtualizar.setBackground(new java.awt.Color(255, 255, 255));
        btAtualizar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAtualizar.setForeground(new java.awt.Color(0, 0, 102));
        btAtualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icAtualizar2.png"))); // NOI18N
        btAtualizar.setText("Atualizar");
        btAtualizar.setEnabled(false);
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 325, 120, 50));

        try {
            tfNumeroQuarto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfNumeroQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumeroQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(tfNumeroQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 90, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/quarto33.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 390));

        setSize(new java.awt.Dimension(497, 425));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private Boolean verificaNumQuarto() {
        if (this.tfNumeroQuarto.getText().equals("    ")) {
            this.tfNumeroQuarto.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    private Boolean verificaCategoria() {
        if (bgCategoria.getSelection() == null) {
            return false;
        } else {
            return true;
        }
    }

    private Boolean verificaNumCamas() {
        if (bgCamas.getSelection() == null) {
            return false;
        } else {
            return true;
        }
    }

    private Boolean verificaRadioButton() {
        if (verificaCategoria()) {
            return verificaNumCamas();
        }

        return false;
    }

    private Boolean verificaCampos() {
        if (verificaNumQuarto()) {
            return verificaRadioButton();
        }

        return false;
    }

    private void preencheDados(Boolean cadastra) {
        Quarto q = new Quarto();
        q.setNumQuarto(Short.parseShort(tfNumeroQuarto.getText()));
        q.setCategoria(bgCategoria.getSelection().getActionCommand());
        q.setNumCamas(Byte.parseByte(bgCamas.getSelection().getActionCommand()));
        q.setValor(Float.parseFloat(tfDiaria.getText()));
        
        if (cadastra)
            FormPrincipal.quartoDAO.adicionarQuarto(q);
        else
            FormPrincipal.quartoDAO.atualizarQuarto(q);
        
        
        JOptionPane.showMessageDialog(null, "Cadastro do quarto realizado com sucesso!", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
        this.limparDados();
    }
    
    private void limparDados(){
        tfNumeroQuarto.setText("");
        bgCategoria.clearSelection();
        bgCamas.clearSelection();
        tfDiaria.setText("0.00");

        tfNumeroQuarto.requestFocus();
    }
    
    public void travaItens(){
        tfNumeroQuarto.setEnabled(false);
        btCadastrar.setEnabled(false);
        btBuscarCPF.setEnabled(false);
        btLimpar.setEnabled(false);
        btAtualizar.setEnabled(true);
    }
    
    public void destravaItens(){
        tfNumeroQuarto.setEnabled(true);
        btCadastrar.setEnabled(true);
        btBuscarCPF.setEnabled(true);
        btLimpar.setEnabled(true);
        btAtualizar.setEnabled(false);
    }

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed

        if (this.verificaCampos()) {
            if (this.tfDiaria.getText().matches("[0-9.]+")) {
                
                Quarto q = FormPrincipal.quartoDAO.buscarQuarto(Short.parseShort(tfNumeroQuarto.getText()));
                if (q != null){
                    JOptionPane.showMessageDialog(null, "Já existe esse numero de quarto cadastrado.", "Aviso", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                this.preencheDados(true);
            } 
            else
                JOptionPane.showMessageDialog(null, "O campo \"Valor da Diária\" não permite letra", "Aviso", JOptionPane.WARNING_MESSAGE);
            
        } else {
            JOptionPane.showMessageDialog(null, "Existe campo sem preencher", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        this.limparDados();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void rbSuitePresidencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbSuitePresidencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbSuitePresidencialActionPerformed

    private void rbQuartoSimplesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbQuartoSimplesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbQuartoSimplesActionPerformed

    private void tfNumeroQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumeroQuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumeroQuartoActionPerformed

    private void btBuscarCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarCPFActionPerformed
        if (this.verificaNumQuarto()){
            Quarto q = FormPrincipal.quartoDAO.buscarQuarto(Short.parseShort(tfNumeroQuarto.getText()));
            if (q != null){
                this.travaItens();
                
                tfNumeroQuarto.setText(q.getNumQuarto() + "");
                tfDiaria.setText(q.getValor() + "");
                
                JRadioButton r;
                Enumeration valores = bgCategoria.getElements();
                
                while(valores.hasMoreElements()){
                    r = (JRadioButton) valores.nextElement();
                    if (r.getActionCommand().equals(q.getCategoria())){
                        r.setSelected(true);
                        break;
                    }
                }
                
                valores = bgCamas.getElements();
                while(valores.hasMoreElements()){
                    r = (JRadioButton) valores.nextElement();
                    if (Byte.parseByte(r.getActionCommand()) == q.getNumCamas()){
                        r.setSelected(true);
                        break;
                    }
                }
                
            }else{
                JOptionPane.showMessageDialog(null, "Quarto não encontrado.", "Aviso", JOptionPane.WARNING_MESSAGE);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Por favor, preencha o numero do quarto antes de pesquisar.", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btBuscarCPFActionPerformed

    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        if (this.verificaCampos()) {
            this.destravaItens();
            
            this.preencheDados(false);
        } else {
            JOptionPane.showMessageDialog(null, "Existe campo sem preencher", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (qt != null){
            this.travaItens();
            
            tfNumeroQuarto.setText(qt.getNumQuarto() + "");
            tfDiaria.setText(qt.getValor() + "");
                
                JRadioButton r;
                Enumeration valores = bgCategoria.getElements();
                
                while(valores.hasMoreElements()){
                    r = (JRadioButton) valores.nextElement();
                    if (r.getActionCommand().equals(qt.getCategoria())){
                        r.setSelected(true);
                        break;
                    }
                }
                
                valores = bgCamas.getElements();
                while(valores.hasMoreElements()){
                    r = (JRadioButton) valores.nextElement();
                    if (Byte.parseByte(r.getActionCommand()) == qt.getNumCamas()){
                        r.setSelected(true);
                        break;
                    }
                }
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormQuarto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormQuarto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgCamas;
    private javax.swing.ButtonGroup bgCategoria;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btBuscarCPF;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButtonCasado;
    private javax.swing.JLabel lbValorDiaria;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    private javax.swing.JRadioButton rbQuartoSimples;
    private javax.swing.JRadioButton rbSuitePresidencial;
    private javax.swing.JRadioButton rbSuiteSimples;
    private javax.swing.JTextField tfDiaria;
    private javax.swing.JFormattedTextField tfNumeroQuarto;
    // End of variables declaration//GEN-END:variables
}
