/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import dao.ClienteDAO;
import dao.QuartoDAO;
import dao.ReservaDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public static ClienteDAO clienteDAO = null;
    public static QuartoDAO quartoDAO = null;
    public static ReservaDAO reservaDAO = null;
    
    public FormPrincipal() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        
        this.clienteDAO = new ClienteDAO();
        this.quartoDAO = new QuartoDAO();
        this.reservaDAO = new ReservaDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbImagemLogo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jCadastrar = new javax.swing.JMenu();
        jClientes = new javax.swing.JMenuItem();
        jQuartos = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemSair = new javax.swing.JMenuItem();
        jReservar = new javax.swing.JMenu();
        jItemReservar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jSobre = new javax.swing.JMenuItem();
        jBuscar = new javax.swing.JMenu();
        jBuscarQuarto = new javax.swing.JMenuItem();
        jBuscarCliente = new javax.swing.JMenuItem();
        jBuscarReserva = new javax.swing.JMenuItem();
        jNotaFiscal = new javax.swing.JMenu();
        jReserva = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema do Hotel Millennium");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new java.awt.BorderLayout());

        lbImagemLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImagemLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/HotelLogo.jpg"))); // NOI18N
        jPanel1.add(lbImagemLogo, java.awt.BorderLayout.CENTER);

        jCadastrar.setText("Cadastrar/Alterar");

        jClientes.setText("Clientes");
        jClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClientesActionPerformed(evt);
            }
        });
        jCadastrar.add(jClientes);

        jQuartos.setText("Quartos");
        jQuartos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jQuartosActionPerformed(evt);
            }
        });
        jCadastrar.add(jQuartos);
        jCadastrar.add(jSeparator1);

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jCadastrar.add(jMenuItemSair);

        jMenuBar1.add(jCadastrar);

        jReservar.setText("Reservar");

        jItemReservar.setText("Reservar");
        jItemReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jItemReservarActionPerformed(evt);
            }
        });
        jReservar.add(jItemReservar);
        jReservar.add(jSeparator2);

        jSobre.setText("Sobre");
        jSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSobreActionPerformed(evt);
            }
        });
        jReservar.add(jSobre);

        jMenuBar1.add(jReservar);

        jBuscar.setText("Buscar");

        jBuscarQuarto.setText("Buscar Quarto");
        jBuscarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarQuartoActionPerformed(evt);
            }
        });
        jBuscar.add(jBuscarQuarto);

        jBuscarCliente.setText("Buscar Cliente");
        jBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarClienteActionPerformed(evt);
            }
        });
        jBuscar.add(jBuscarCliente);

        jBuscarReserva.setText("Buscar Reserva");
        jBuscarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBuscarReservaActionPerformed(evt);
            }
        });
        jBuscar.add(jBuscarReserva);

        jMenuBar1.add(jBuscar);

        jNotaFiscal.setText("Nota Fiscal");
        jNotaFiscal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jNotaFiscalActionPerformed(evt);
            }
        });

        jReserva.setText("Reserva");
        jReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jReservaActionPerformed(evt);
            }
        });
        jNotaFiscal.add(jReserva);

        jMenuBar1.add(jNotaFiscal);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(476, 407));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSobreActionPerformed
        new FormSobre().setVisible(true);
    }//GEN-LAST:event_jSobreActionPerformed

    private void jItemReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jItemReservarActionPerformed
        new FormReserva().setVisible(true);
    }//GEN-LAST:event_jItemReservarActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jQuartosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jQuartosActionPerformed
        new FormQuarto().setVisible(true);
    }//GEN-LAST:event_jQuartosActionPerformed

    private void jClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClientesActionPerformed
        new FormCliente().setVisible(true);
    }//GEN-LAST:event_jClientesActionPerformed

    private void jBuscarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarQuartoActionPerformed
        new FormBuscarQuarto().setVisible(true);
    }//GEN-LAST:event_jBuscarQuartoActionPerformed

    private void jBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarClienteActionPerformed
        new FormBuscarCliente().setVisible(true);
    }//GEN-LAST:event_jBuscarClienteActionPerformed

    private void jBuscarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBuscarReservaActionPerformed
        new FormBuscarReserva().setVisible(true);
    }//GEN-LAST:event_jBuscarReservaActionPerformed

    private void jNotaFiscalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jNotaFiscalActionPerformed
        
    }//GEN-LAST:event_jNotaFiscalActionPerformed

    private void jReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jReservaActionPerformed
        new FormEmissaoNota().setVisible(true);
    }//GEN-LAST:event_jReservaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jBuscar;
    private javax.swing.JMenuItem jBuscarCliente;
    private javax.swing.JMenuItem jBuscarQuarto;
    private javax.swing.JMenuItem jBuscarReserva;
    private javax.swing.JMenu jCadastrar;
    private javax.swing.JMenuItem jClientes;
    private javax.swing.JMenuItem jItemReservar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jNotaFiscal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuItem jQuartos;
    private javax.swing.JMenuItem jReserva;
    private javax.swing.JMenu jReservar;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem jSobre;
    private javax.swing.JLabel lbImagemLogo;
    // End of variables declaration//GEN-END:variables
}
