/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Cliente;
import classes.Quarto;
import classes.Reserva;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuário
 */
public class FormReserva extends javax.swing.JFrame {
    private Boolean pesquisouCliente = false;
    private Boolean pesquisouQuarto = false;
    /**
     * Creates new form FormReserva
     */
    public FormReserva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfCpf = new javax.swing.JFormattedTextField();
        lbCpfCliente = new javax.swing.JLabel();
        lbResultado = new javax.swing.JLabel();
        tfDataInicio = new javax.swing.JFormattedTextField();
        lbValor = new javax.swing.JLabel();
        lbNumeroQuarto = new javax.swing.JLabel();
        btOrcamento = new javax.swing.JButton();
        btBuscarQuarto = new javax.swing.JButton();
        lbDiasHospedagem = new javax.swing.JLabel();
        btBuscarCliente = new javax.swing.JButton();
        lbDataInicio = new javax.swing.JLabel();
        tfDiasHospedagem = new javax.swing.JTextField();
        btCadastrar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        tfNumeroQuarto = new javax.swing.JFormattedTextField();
        lbImagemReserva = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Criar uma Reserva");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        try {
            tfCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfCpfActionPerformed(evt);
            }
        });
        getContentPane().add(tfCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 100, 30));

        lbCpfCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbCpfCliente.setForeground(new java.awt.Color(0, 0, 102));
        lbCpfCliente.setText("CPF do Cliente:");
        getContentPane().add(lbCpfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 100, 30));

        lbResultado.setForeground(new java.awt.Color(0, 0, 102));
        lbResultado.setText("0");
        getContentPane().add(lbResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 110, 20));

        try {
            tfDataInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(tfDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 90, 80, 30));

        lbValor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbValor.setForeground(new java.awt.Color(0, 0, 102));
        lbValor.setText("Valor:");
        getContentPane().add(lbValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 110, 20));

        lbNumeroQuarto.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNumeroQuarto.setForeground(new java.awt.Color(0, 0, 102));
        lbNumeroQuarto.setText("Número do Quarto:");
        getContentPane().add(lbNumeroQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 142, 110, 20));

        btOrcamento.setForeground(new java.awt.Color(0, 0, 102));
        btOrcamento.setText("Orçamento");
        btOrcamento.setEnabled(false);
        btOrcamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrcamentoActionPerformed(evt);
            }
        });
        getContentPane().add(btOrcamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        btBuscarQuarto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icBuscar.png"))); // NOI18N
        btBuscarQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(btBuscarQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 40, 30));

        lbDiasHospedagem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDiasHospedagem.setForeground(new java.awt.Color(0, 0, 102));
        lbDiasHospedagem.setText("Dias de Hospedagem:");
        getContentPane().add(lbDiasHospedagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 142, 130, 20));

        btBuscarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icBuscar.png"))); // NOI18N
        btBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btBuscarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 40, 30));

        lbDataInicio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbDataInicio.setForeground(new java.awt.Color(0, 0, 102));
        lbDataInicio.setText("Data de Início:");
        getContentPane().add(lbDataInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, -1, 20));
        getContentPane().add(tfDiasHospedagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 80, -1));

        btCadastrar.setBackground(new java.awt.Color(255, 255, 255));
        btCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCadastrar.setForeground(new java.awt.Color(0, 0, 102));
        btCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icIncluirCliente.png"))); // NOI18N
        btCadastrar.setText("Cadastrar");
        btCadastrar.setEnabled(false);
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(btCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, 51));

        btLimpar.setBackground(new java.awt.Color(255, 255, 255));
        btLimpar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(0, 0, 102));
        btLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icLimpar.png"))); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, 120, 51));

        btSair.setBackground(new java.awt.Color(255, 255, 255));
        btSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSair.setForeground(new java.awt.Color(0, 0, 102));
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icSair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, 51));

        try {
            tfNumeroQuarto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tfNumeroQuarto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumeroQuartoActionPerformed(evt);
            }
        });
        getContentPane().add(tfNumeroQuarto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 60, 30));

        lbImagemReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Reserva55.jpg"))); // NOI18N
        getContentPane().add(lbImagemReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 360));

        setSize(new java.awt.Dimension(499, 392));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private Boolean verificaCPF() {
        if (this.tfCpf.getText().equals("   .   .   -  ")) {
            this.tfCpf.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    private Boolean verificaData() {
        if (this.tfDataInicio.getText().equals("  /  /    ")) {
            this.tfDataInicio.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    private Boolean verificaNumQuarto() {
        if (this.tfNumeroQuarto.getText().equals("    ")) {
            this.tfNumeroQuarto.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    private Boolean verificaMascara() {
        if (verificaCPF()) {
            if (verificaData()) {
                return verificaNumQuarto();
            }
        }

        return false;
    }

    private Boolean verificaDiaHospedagem() {
        if (this.tfDiasHospedagem.getText().equals("")) {
            tfDiasHospedagem.requestFocus();
            return false;
        } else {
            return true;
        }
    }

    private Boolean verificaCampos() {
        if (verificaMascara()) {
            return verificaDiaHospedagem();
        }

        return false;
    }
    
    private void limparDados(){
        tfCpf.setText("");
        tfNumeroQuarto.setText("");
        tfDataInicio.setText("");
        tfDiasHospedagem.setText("");
        
        tfCpf.setEnabled(true);
        tfNumeroQuarto.setEnabled(true);
        btCadastrar.setEnabled(false);
        btOrcamento.setEnabled(false);
        
        pesquisouCliente = false;
        pesquisouQuarto = false;

        tfCpf.requestFocus();
    }
    
    public void preencheDados(){
        Reserva r = new Reserva();
        
        Cliente c = FormPrincipal.clienteDAO.buscarCliente(tfCpf.getText());
        r.setCliente(c);
        
        Quarto q = FormPrincipal.quartoDAO.buscarQuarto(Short.parseShort(tfNumeroQuarto.getText()));
        r.setQuarto(q);
        
        r.setDiasHospedagem(Short.parseShort(tfDiasHospedagem.getText()));
        
        int num = FormPrincipal.reservaDAO.getList().size() + 1;
        r.setId((short) num);
        
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        try {
            df.setLenient(false);
            Date dt = df.parse(tfDataInicio.getText());
            r.setDataInicio(dt);
            
            FormPrincipal.reservaDAO.adicionarReserva(r);
            r.getQuarto().setOcupado(true);
            
            JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso!", "Cadastro", JOptionPane.INFORMATION_MESSAGE);
            this.limparDados();
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Data Invalida", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void tfCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfCpfActionPerformed

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        if (verificaCampos()) {
            if (this.tfDiasHospedagem.getText().matches("[0-9]+")) {
                this.preencheDados();
            } 
            else
                JOptionPane.showMessageDialog(null, "O campo \"Dias de Hospedagem\" permite apenas número", "Aviso", JOptionPane.WARNING_MESSAGE);
            
        }
        else
            JOptionPane.showMessageDialog(null, "Existe campo sem preencher", "Aviso", JOptionPane.WARNING_MESSAGE);
        
    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        this.limparDados();
    }//GEN-LAST:event_btLimparActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void tfNumeroQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumeroQuartoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumeroQuartoActionPerformed

    private void btBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarClienteActionPerformed
        if (verificaCPF()) {
            Cliente c = FormPrincipal.clienteDAO.buscarCliente(tfCpf.getText());
            if (c != null) {
                tfCpf.setEnabled(false);
                
                this.pesquisouCliente = true;
                if (this.pesquisouQuarto)
                    btCadastrar.setEnabled(true);
            }
            else
                JOptionPane.showMessageDialog(null, "Cliente não encontrado", "Atenção", JOptionPane.WARNING_MESSAGE);
            
        }
        else
            JOptionPane.showMessageDialog(null, "Preencha o campo antes de pesquisar", "Atenção", JOptionPane.WARNING_MESSAGE);
        
    }//GEN-LAST:event_btBuscarClienteActionPerformed

    private void btBuscarQuartoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarQuartoActionPerformed
        if (verificaNumQuarto()) {
            Quarto q = FormPrincipal.quartoDAO.buscarQuarto(Short.parseShort(tfNumeroQuarto.getText()));
            if (q != null) {
                if (q.getOcupado()){
                    JOptionPane.showMessageDialog(null, "Esse quarto já está ocupado.", "Atenção", JOptionPane.WARNING_MESSAGE);
                    return;
                }
                
                tfNumeroQuarto.setEnabled(false);
                this.pesquisouQuarto = true;
                this.btOrcamento.setEnabled(true);
                
                if (this.pesquisouCliente)
                    btCadastrar.setEnabled(true);
            }
            else
                JOptionPane.showMessageDialog(null, "Quarto não encontrado", "Atenção", JOptionPane.WARNING_MESSAGE);
            
        } 
        else
            JOptionPane.showMessageDialog(null, "Preencha o campo antes de pesquisar", "Atenção", JOptionPane.WARNING_MESSAGE);
        
    }//GEN-LAST:event_btBuscarQuartoActionPerformed

    private void btOrcamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrcamentoActionPerformed
        if (verificaDiaHospedagem()){
            if (this.tfDiasHospedagem.getText().matches("[0-9]+")){
                Quarto q = FormPrincipal.quartoDAO.buscarQuarto(Short.parseShort(tfNumeroQuarto.getText()));
                float valor = q.getValor() * Integer.parseInt(tfDiasHospedagem.getText());
                lbResultado.setText(valor + "");
            }
            else
                JOptionPane.showMessageDialog(null, "O campo \"Orçamento\" não permite o uso de letras.", "Aviso", JOptionPane.WARNING_MESSAGE);
        }
        else
            JOptionPane.showMessageDialog(null, "O campo \"Orçamento\" está em branco", "Aviso", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btOrcamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormReserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarCliente;
    private javax.swing.JButton btBuscarQuarto;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btOrcamento;
    private javax.swing.JButton btSair;
    private javax.swing.JLabel lbCpfCliente;
    private javax.swing.JLabel lbDataInicio;
    private javax.swing.JLabel lbDiasHospedagem;
    private javax.swing.JLabel lbImagemReserva;
    private javax.swing.JLabel lbNumeroQuarto;
    private javax.swing.JLabel lbResultado;
    private javax.swing.JLabel lbValor;
    private javax.swing.JFormattedTextField tfCpf;
    private javax.swing.JFormattedTextField tfDataInicio;
    private javax.swing.JTextField tfDiasHospedagem;
    private javax.swing.JFormattedTextField tfNumeroQuarto;
    // End of variables declaration//GEN-END:variables
}
