/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import classes.Reserva;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author diego
 */
public class FormEmissaoNota extends javax.swing.JFrame {

    /**
     * Creates new form FormEmissaoNota
     */
    public FormEmissaoNota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNReserva = new javax.swing.JLabel();
        tfId = new javax.swing.JTextField();
        btBuscarReserva = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taDados = new javax.swing.JTextArea();
        btCancelar = new javax.swing.JButton();
        btSair = new javax.swing.JButton();
        btEmitir = new javax.swing.JButton();
        lbImagemNota = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbNReserva.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lbNReserva.setForeground(new java.awt.Color(0, 0, 102));
        lbNReserva.setText("Nº Reserva:");
        getContentPane().add(lbNReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));
        getContentPane().add(tfId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 80, 30));

        btBuscarReserva.setBackground(new java.awt.Color(255, 255, 255));
        btBuscarReserva.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btBuscarReserva.setForeground(new java.awt.Color(0, 0, 102));
        btBuscarReserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icBuscar.png"))); // NOI18N
        btBuscarReserva.setText("Buscar");
        btBuscarReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarReservaActionPerformed(evt);
            }
        });
        getContentPane().add(btBuscarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 40, 110, 50));

        taDados.setColumns(20);
        taDados.setLineWrap(true);
        taDados.setRows(5);
        jScrollPane1.setViewportView(taDados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 430, 180));

        btCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btCancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCancelar.setForeground(new java.awt.Color(0, 0, 102));
        btCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 330, 120, 51));

        btSair.setBackground(new java.awt.Color(255, 255, 255));
        btSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btSair.setForeground(new java.awt.Color(0, 0, 102));
        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icSair.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, -1, 51));

        btEmitir.setBackground(new java.awt.Color(255, 255, 255));
        btEmitir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btEmitir.setForeground(new java.awt.Color(0, 0, 102));
        btEmitir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icNotaFiscal.png"))); // NOI18N
        btEmitir.setText("Emitir N.F.");
        btEmitir.setEnabled(false);
        btEmitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEmitirActionPerformed(evt);
            }
        });
        getContentPane().add(btEmitir, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 130, 50));

        lbImagemNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/notaFiscal.jpg"))); // NOI18N
        getContentPane().add(lbImagemNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 420));

        setSize(new java.awt.Dimension(515, 455));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btBuscarReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarReservaActionPerformed
        if (tfId.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Preencha o campo antes de pesquisar.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else if (!this.tfId.getText().matches("[0-9]+")){
            JOptionPane.showMessageDialog(null, "Apenas número são permitidos no campo.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Reserva r = FormPrincipal.reservaDAO.buscarReserva(Short.parseShort(tfId.getText()));
        taDados.setText("");
        
        if (r !=  null){
            taDados.append(r.toString() + "\n");
            taDados.append(r.getCliente().toString() + "\n");
            taDados.append(r.getQuarto().toString());
            btEmitir.setEnabled(true);
        }
        else{
            btEmitir.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Reserva não encontrada.", "Atenção", JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btBuscarReservaActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        tfId.setText("");
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btSairActionPerformed

    private void btEmitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEmitirActionPerformed
       File arq = new File("C:\\NotaFiscal_"+tfId.getText()+".txt");
       if(!arq.exists())
       {
           try {
               
               arq.createNewFile();
           } catch (IOException ex) {
               JOptionPane.showMessageDialog(null, "Não foi poossivel criar o arquivo!", "Atenção",JOptionPane.ERROR_MESSAGE);
           }
       }
       
        try {
            FileWriter fw = new FileWriter(arq);
            BufferedWriter bw = new BufferedWriter(fw);
            
            String vet[] = taDados.getText().split("\n");
            for(String linha: vet)
            {
                bw.write(linha);
                bw.newLine();
            }

            bw.close();
            fw.close();
            
            JOptionPane.showMessageDialog(null, "Nota Fiscal foi criada com sucesso em C:\\!", "Atenção",JOptionPane.INFORMATION_MESSAGE);
            
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Não foi poossivel abrir o arquivo!", "Atenção",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btEmitirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEmissaoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEmissaoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEmissaoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEmissaoNota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEmissaoNota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBuscarReserva;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEmitir;
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbImagemNota;
    private javax.swing.JLabel lbNReserva;
    private javax.swing.JTextArea taDados;
    private javax.swing.JTextField tfId;
    // End of variables declaration//GEN-END:variables
}
